#!/usr/bin/env python3

import os
import sys

from cc_pathlib import Path

import spext.proxy

repo_dir = Path(os.environ['SPEXT_repo_DIR']).resolve()

key = sys.argv[1]
p_ident = int(sys.argv[2])

s = spext.proxy.SpextProxy(repo_dir, True)
s._prep_section(key, p_ident)
